stages:
  - docker

variables:
  ARGO_VERSION: "2.0.4"
  KSOPS_VERSION: "v2.6.0"
  PKG_NAME: "ksops"

docker:
  image: docker:20.10.8
  stage: docker
  services:
    - docker:20.10.8-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - "export build_timestamp=v$(cat .timestamp)"
    - docker build -t $IMAGE_NAME:$build_timestamp -t $IMAGE_NAME:latest . --build-arg GIT_COMMIT_SHA=$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:$build_timestamp
    - docker push $IMAGE_NAME:latest
  only:
    - master
    - merge_requests
