stages:
  - docker

variables:
  ARGO_CD_VERSION: "v2.1.0"
  KSOPS_VERSION: "v2.6.0"
  KSOPS_PKG_NAME: "ksops"

docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - "export build_timestamp=v$(date +%Y%m%d%H%M%S)"
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest --destination $CI_REGISTRY_IMAGE:$build_timestamp --build-arg ARGO_CD_VERSION=$ARGO_CD_VERSION --build-arg KSOPS_VERSION=$KSOPS_VERSION --build-arg PKG_NAME=$KSOPS_PKG_NAME --label GIT_COMMIT_SHA=$CI_COMMIT_SHA --label TIMESTAMP=$build_timestamp
  only:
    - main
