on:
  workflow_call:
    inputs:
      push:
        description: "Whether to publish images to GHCR"
        required: true
        type: boolean

env:
  image: ghcr.io/shivjm/argocd
  helmSecrets: v3.10.0
  jb: master
  jsonnet: v0.17.0
  gojsontoyaml: v0.1.0

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        argo:
          - v2.1.0
          - v2.1.1
          - v2.1.2
          - v2.1.3
          - v2.1.4
          - v2.1.5
          - v2.1.6
          - v2.1.7
          # - v2.0.5 # official image uses `USER argocd` instead of `USER 999`
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: ${{ inputs.push == true }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # TODO use dockerfile-image-tags to parse tool versions where possible
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.image }}
          labels: |
            tools.helmsecrets.version=${{ env.helmSecrets }}
            tools.jsonnetBundler.commit=${{ env.jb }}
            tools.jsonnet.version=${{ env.jsonnet }}
            tools.gojsontoyaml.version=${{ env.gojsontoyaml }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=${{ env.image }}
          cache-to: type=inline
          build-args: |
            ARGOCD_VERSION=${{ matrix.argo }}
            KSOPS_VERSION=${{ env.ksops }}
            HELM_SECRETS_VERSION=${{ env.helmSecrets }}
            JSONNET_BUNDLER_COMMIT=${{ env.jb }}
            GOJSONNET_VERSION=${{ env.jsonnet }}
            GOJSONTOYAML_VERSION=${{ env.gojsontoyaml }}
          tags: "${{ env.image }}:${{ matrix.argo }}" # ignore metadata-action tags
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ inputs.push == true }}
