name: Build and publish to Docker Hub

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

env:
  image: ghcr.io/shivjm/argocd-ksops-helm-secrets

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        argo:
          - v2.1.0
          - v2.1.1
          # - v2.0.5 # official image uses `USER argocd` instead of `USER 999`
        ksops:
          - v2.6.0
        helmSecrets:
          - v3.8.3
        go:
          - 1.17.0
        jb:
          - master
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.image }}
          labels: |
            tools.helmsecrets.version=${{ matrix.helmSecrets }}
            tools.ksops.version=${{ matrix.ksops }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=${{ env.image }}
          cache-to: type=inline
          build-args: |
            ARGOCD_VERSION=${{ matrix.argo }}
            KSOPS_VERSION=${{ matrix.ksops }}
            HELM_SECRETS_VERSION=${{ matrix.helmSecrets }}
            GO_VERSION=${{ matrix.go }}
            JSONNET_BUNDLER_VERSION=${{ matrix.jb }}
          tags: "${{ env.image }}:${{ matrix.argo }}" # ignore metadata-action tags
          labels: ${{ steps.meta.outputs.labels }}
          push: true
