name: Test build

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - README.md

jobs:
  build:
    uses: "./.github/workflows/docker.yml"
    with:
      push: false
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
