name: Test build

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - README.md

jobs:
  build:
    uses: "shivjm/docker-argocd/.github/workflows/docker.yml@50176fd3a0a2c850d07bcde01fd4e598f2992b25"
    with:
      push: false
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3
