name: Test build

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - README.md

jobs:
  build:
    uses: "shivjm/docker-argocd/.github/workflows/docker.yml@57e24bc1b0b15b3675aac9ae902c1c042528a628"
    with:
      push: false
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
