name: Test build

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - README.md

jobs:
  build:
    uses: "shivjm/docker-argocd/.github/workflows/docker.yml@358c5031517b308b1914a2df00dfb538922711a5"
    with:
      push: false
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
